packages:
  - 'packages/common'
  - 'packages/ui'
  - 'packages/core'
  - 'packages/scaffold'
  - 'packages/scaffold-utils'
  - 'packages/scaffold-ui'
  - 'packages/scaffold-react'
  - 'packages/scaffold-vue'
  - 'packages/polyfills'
  - 'packages/wallet'
  - 'packages/siwe'
  - 'packages/wagmi'
  - 'packages/ethers'
  - 'packages/ethers5'
  - 'packages/solana'
  - 'packages/cdn'
  - 'apps/*'
  - 'examples/*'
