name: Realease NPM packages

on:
  workflow_dispatch:

  push:
    branches:
      - V3

jobs:
  release-package:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@ridotto-io'
      - name: PRE Publish
        run: |
          npm i
          npm run build:clean
          npm run build
      - name: Publish
        run: |
          cd packages/common/
          npm publish
      - name: Publish
        run: |
          cd packages/core/
          npm publish
      - name: Publish
        run: |
          cd packages/polyfills/
          npm publish
      - name: Publish
        run: |
          cd packages/wallet/
          npm publish
      - name: Publish
        run: |
          cd packages/ui/
          npm publish
      - name: Publish
        run: |
          cd packages/scaffold/
          npm publish
      - name: Publish
        run: |
          cd packages/scaffold-utils/
          npm publish
      - name: Publish
        run: |
          cd packages/scaffold-vue/
          npm publish
      - name: Publish
        run: |
          cd packages/scaffold-react/
          npm publish
      - name: Publish
        run: |
          cd packages/siwe/
          npm publish
      - name: Publish
        run: |
          cd packages/wagmi/
          npm publish
      - name: Publish
        run: |
          cd packages/ethers/
          npm publish
      - name: Publish
        run: |
          cd packages/ethers5/
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
