name: TEMPORAL Realease NPM packages

on:
  workflow_dispatch:

  push:
    branches:
      - V3-deprecated

jobs:
  release-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@ridotto-io'
      - name: Install npm packages
        run: |
          cd packages/ethers5/
          npm install --legacy-peer-deps
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
